apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nlp-ingress-front
  namespace: nlp
spec:
  ingressClassName: nginx
  rules:
    - host: 34.40.49.244.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nlp-front-svc
                port:
                  number: 80
